---
schema:
  procedures: {}
  tables:
    role:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        date_created:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_created
          order: 1
          size:
            - 0
        date_modified:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_modified
          order: 2
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 3
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 4
          size:
            - 50
      indices: []
      name: role
      options: []
      order: 1
    stat:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        date_created:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_created
          order: 1
          size:
            - 0
        date_modified:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_modified
          order: 2
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 3
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 4
          size:
            - 50
      indices: []
      name: stat
      options: []
      order: 2
    user:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        date_created:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_created
          order: 1
          size:
            - 0
        date_modified:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_modified
          order: 2
          size:
            - 0
        hostmask:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: hostmask
          order: 4
          size:
            - 100
        id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 3
          size:
            - 0
        lastfm:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: lastfm
          order: 6
          size:
            - 20
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 5
          size:
            - 45
      indices: []
      name: user
      options: []
      order: 3
    user_role:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - role_id
          match_type: ''
          name: user_role_fk_role_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: role
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: user_role_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        date_created:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_created
          order: 1
          size:
            - 0
        date_modified:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_modified
          order: 2
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 3
          size:
            - 0
        role_id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: role_id
          order: 5
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 4
          size:
            - 0
      indices:
        - fields:
            - role_id
          name: user_role_idx_role_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: user_role_idx_user_id
          options: []
          type: NORMAL
      name: user_role
      options: []
      order: 4
    user_stat:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - stat_id
          match_type: ''
          name: user_stat_fk_stat_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: stat
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: user_stat_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: user
          type: FOREIGN KEY
      fields:
        date_created:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_created
          order: 1
          size:
            - 0
        date_modified:
          data_type: datetime
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: date_modified
          order: 2
          size:
            - 0
        id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 3
          size:
            - 0
        stat_id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: stat_id
          order: 5
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          extra:
            unsigned: 1
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 4
          size:
            - 0
      indices:
        - fields:
            - stat_id
          name: user_stat_idx_stat_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: user_stat_idx_user_id
          options: []
          type: NORMAL
      name: user_stat
      options: []
      order: 5
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Role
      - Stat
      - User
      - UserRole
      - UserStat
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
