sudo: false
language: perl
perl:
    - '5.22.1'
addons:
    apt:
        packages:
            - libdb-dev
matrix:
    allow_failures:
        - perl: 'blead'
        - perl: '5.8'
fast_finish: true
branches:
    only:
        - master
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
install:
    - cpanm --notest Dist::Zilla
    - "/home/travis/perl5/bin/dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
    - "/home/travis/perl5/bin/dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
    - /home/travis/perl5/bin/dzil smoke --release --author
