sudo: false
language: perl
perl:
    - '5.22.1'
addons:
    apt:
        packages:
            - libdb-dev
matrix:
    allow_failures:
        - perl: 'blead'
        - perl: '5.8'
fast_finish: true
branches:
    only:
        - master
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init --auto
install:
    - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
    - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
    - dzil smoke --release --author
