sudo: false
language: perl
perl:
   - '5.22'
matrix:
   fast_finish: true
before_install:
   - git config --global user.name "Travis CI"
   - git config --global user.email "mike+travis@netsplit.org.uk"
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose --no-interactive --notest"
script:
   - dzil smoke --release --author
