sudo: false
language: perl
perl:
   - '5.21'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - sudo apt-get -qq update
   - sudo apt-get install -y libcdb-file-perl libdb-file-lock-perl libmldbm-perl libtie-persistent-perl
install:
   - cpanm --quiet --notest Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
   - dzil smoke --release --author
